// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNaxqG5dOIieEoIoZHfuqK9hUCR6HoSss',
    appId: '1:26467411857:web:12c182135934ade83c9c30',
    messagingSenderId: '26467411857',
    projectId: 'muhtaj-f3440',
    authDomain: 'muhtaj-f3440.firebaseapp.com',
    storageBucket: 'muhtaj-f3440.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqIdFpHLHW7-dFUwGSLkfdzZrsl0oou8',
    appId: '1:26467411857:android:2f08f91e60833f593c9c30',
    messagingSenderId: '26467411857',
    projectId: 'muhtaj-f3440',
    storageBucket: 'muhtaj-f3440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg5xF2DyMNnTGbd0BToSzNOkk6GrAAeek',
    appId: '1:26467411857:ios:5778e20339c814653c9c30',
    messagingSenderId: '26467411857',
    projectId: 'muhtaj-f3440',
    storageBucket: 'muhtaj-f3440.firebasestorage.app',
    iosBundleId: 'com.layra.mohtaaj',
  );
}
